version: "3.7"
services:

  # DATABASE
  database:
    image: postgres:13.1
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:4210:5432"
    env_file: ./env/.env.postgres

  # BACKEND
  api:
    build:
      dockerfile: ./Dockerfile
      context: ./api
    # env_file:
    #   - ./env/.env.global
    #   - ./env/.env.api
    volumes:
      - ./api:/app
    ports:
      - "127.0.0.1:8080:8080"

  # FRONTEND
  app:
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "127.0.0.1:3000:8080"
    stdin_open: true
  
  # # AUTH
  # supertokens:
  #   image: "registry.supertokens.io/supertokens/supertokens-postgresql"
  #   ports:
  #     - "127.0.0.1:3567:3567"

volumes:
  database:
    name: database
